"use client";
import {useState,useEffect,useRef,useCallback} from 'react';
import {Flame,Wind,Mountain,Droplets,Moon,Sun,Sparkles,Users,KeyRound,Copy,Check,ArrowRight,Shield,RefreshCw,Download,Flag,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {CreatureArt} from './creature-art';
import {TypeBadge,Health,Effects,MonsterDetails,RulesDialog} from './game-details';
import {SPECIES,SETS,MOVES,effectiveness} from '@/lib/game/content';
import {damage,effective} from '@/lib/game/math';
import type {View,Choice,Battler,Player} from '@/lib/game/types';

type Session={room:string;token:string};
type Tool={name:string;description:string;title:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown|Promise<unknown>};
type ModelContext={registerTool:(tool:Tool,options:{signal:AbortSignal})=>unknown};
const opposite=(p:Player):Player=>p===0?1:0;
const choiceKey=(c:Choice)=>c.kind==='move'?'move:'+c.move:c.kind==='lead'||c.kind==='switch'?c.kind+':'+c.slot:c.kind;
async function request<T>(path:string,session:Session|null,body?:unknown):Promise<T>{
 const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:{...(session?{Authorization:'Bearer '+session.token}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{}),cache:'no-store'});
 const data=await res.json() as T&{error?:string};if(!res.ok)throw Error(data.error??'The room could not be reached. Please retry.');return data;
}
function TeamCard({mon,selected=false,onSelect,label}:{mon:Battler;selected?:boolean;onSelect?:()=>void;label?:string}){
 const m=SPECIES[mon.monster_id],set=SETS[mon.set_id];
 return <article className={'team-card '+(selected?'selected ':'')+(mon.hp===0?'fainted':'')}>
 <div className="team-card-heading"><TypeBadge type={m.type}/><MonsterDetails mon={mon} compact/></div>
 <CreatureArt id={m.id}/><h3>{m.name}</h3><span className="set-name">{set.name}</span><Health mon={mon}/>
 <div className="card-speed">Speed {effective(mon,'speed')} · {m.stats.force>=m.stats.spirit?'Force':'Spirit'} attacker</div>
 <Effects mon={mon}/><div className="card-moves">{set.move_ids.map(id=><span key={id}>{MOVES[id].name}</span>)}</div>
 {onSelect&&<Button variant={selected?'default':'outline'} onClick={onSelect} className="choose-card">{selected?<Check size={15}/>:<ArrowRight size={15}/>} {label??'Choose companion'}</Button>}
 </article>;
}
function ActiveCard({mon,side}:{mon:Battler|null;side:string}){
 if(!mon)return <div className="active-card empty-active"><span className="eyebrow">{side}</span><Shield size={50}/><h2>Choosing a lead</h2><p>The choice stays secret.</p></div>;
 const m=SPECIES[mon.monster_id];return <div className={'active-card '+(mon.hp===0?'fainted':'')}><div className="active-caption"><span className="eyebrow">{side}</span><TypeBadge type={m.type}/></div><div className="active-name"><h2>{m.name}</h2><MonsterDetails mon={mon} compact/></div><Health mon={mon}/><div className="active-speed">Speed {effective(mon,'speed')} <span>· {SETS[mon.set_id].name}</span></div><Effects mon={mon}/></div>;
}
export default function GameClient(){
 const [code,setCode]=useState(''),[session,setSession]=useState<Session|null>(null),[view,setView]=useState<View|null>(null),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[picked,setPicked]=useState<Choice|null>(null),[redrawOpen,setRedrawOpen]=useState(false),[resignOpen,setResignOpen]=useState(false),[confidence,setConfidence]=useState(''),[fun,setFun]=useState(''),[clarity,setClarity]=useState(''),[agency,setAgency]=useState(''),[again,setAgain]=useState(''),[comment,setComment]=useState(''),[feedbackSaved,setFeedbackSaved]=useState(false);
 const current=useRef<{session:Session|null;view:View|null}>({session:null,view:null});
 current.current={session,view};
 const accept=useCallback((next:View)=>{setView(old=>!old||next.room!==old.room||next.version>=old.version?next:old);},[]);
 useEffect(()=>{
  const room=new URLSearchParams(location.search).get('room')?.toUpperCase()??'';setCode(room);
  const token=room?(sessionStorage.getItem('lantern-seat:'+room)??localStorage.getItem('lantern-seat:'+room)):null;
  if(token){const s={room,token};setSession(s);request<View>('/api/rooms/'+room,s).then(accept).catch(e=>setError(e.message)).finally(()=>setReady(true));}
  else setReady(true);
 },[accept]);
 useEffect(()=>{if(!session)return;let stopped=false;const poll=async()=>{try{const next=await request<View>('/api/rooms/'+session.room,session);if(!stopped){accept(next);setError('');}}catch(e){if(!stopped)setError(e instanceof Error?e.message:'Connection paused. Your contest is saved.');}};const timer=setInterval(poll,2000);return()=>{stopped=true;clearInterval(timer);};},[session,accept]);
 useEffect(()=>{setPicked(null);setConfidence('');},[view?.game.gateId]);
 async function openRoom(join?:string){setBusy(true);setError('');try{const result=await request<{token:string;view:View}>('/api/rooms',null,join?{code:join}:{}),s={room:result.view.room,token:result.token};sessionStorage.setItem('lantern-seat:'+s.room,s.token);localStorage.setItem('lantern-seat:'+s.room,s.token);setSession(s);accept(result.view);history.replaceState(null,'','?room='+s.room);setNotice('');return result.view;}catch(e){const message=e instanceof Error?e.message:'Could not open room.';setError(message);throw e;}finally{setBusy(false);}}
 async function commitChoice(choice:Choice,gate?:number){const latest=current.current;if(!latest.session||!latest.view)throw Error('Open a room first.');if(!latest.view.joined)throw Error('Invite an opponent first.');setBusy(true);setError('');try{
  if((confidence||choice.kind==='redraw'&&comment)&&(latest.view.game.gate==='offer'||latest.view.game.gate==='lead'))await request('/api/rooms/'+latest.session.room,latest.session,{feedback:{stage:latest.view.game.gate==='offer'?'first_offer':'final_team',answers:{workable_plan:confidence||null,redraw_reason:choice.kind==='redraw'?comment.slice(0,500):null}}});
  const next=await request<View>('/api/rooms/'+latest.session.room,latest.session,{gate:gate??latest.view.game.gateId,choice});accept(next);setPicked(null);setRedrawOpen(false);setResignOpen(false);return next;
 }catch(e){setError(e instanceof Error?e.message:'Could not commit. Retry the same choice.');throw e;}finally{setBusy(false);}}
 const actions=useRef({openRoom,commitChoice});actions.current={openRoom,commitChoice};
 useEffect(()=>{
  const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const schema=(properties:object,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
  const settled=async(v:View)=>{await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {room:v.room,player:v.player,gate:v.game.gate,gateId:v.game.gateId,turn:v.game.turn,committed:v.game.committed,outcome:v.game.outcome};};
  const tools:Tool[]=[
   {name:'lantern_create_room',title:'Create contest room',description:'Create a real private two-player room, receive a random team, and show its invite code.',inputSchema:schema({}),annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{if(input&&typeof input==='object'&&Object.keys(input).length===0)return settled(await actions.current.openRoom());throw Error('Expected an empty object.');}},
   {name:'lantern_join_room',title:'Join contest room',description:'Claim the second seat of an existing private room and show your independently generated team.',inputSchema:schema({code:{type:'string',pattern:'^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{8}$'}},['code']),annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{const c=(input as {code?:unknown})?.code;if(typeof c!=='string'||!/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{8}$/.test(c))throw Error('A valid 8-character room code is required.');return settled(await actions.current.openRoom(c));}},
   {name:'lantern_read_contest',title:'Read visible contest',description:'Read this player’s visible teams, current effects, turn, legal choices and commitment state. Never reveals secret opponent choices.',inputSchema:schema({}),annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>current.current.view??{status:'No room open'}},
   {name:'lantern_commit_choice',title:'Commit contest choice',description:'Commit a final secret choice at the displayed gate: keep/redraw, lead, move, switch, or resign. Uses the same rules as the visible buttons.',inputSchema:schema({gate:{type:'integer',minimum:1},choice:{type:'object',properties:{kind:{enum:['keep','redraw','lead','move','switch','resign']},slot:{type:'integer',minimum:0,maximum:3},move:{type:'string'}},required:['kind'],additionalProperties:false}},['gate','choice']),annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{const i=input as {gate:number;choice:Choice};if(!i||!Number.isInteger(i.gate)||!i.choice)throw Error('Gate and choice are required.');return settled(await actions.current.commitChoice(i.choice,i.gate));}}
  ];for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 async function copyInvite(){try{await navigator.clipboard.writeText(location.origin+'/?room='+view!.room);setNotice('Invite link copied.');}catch{setNotice('Share the room code shown above with your friend.');}}
 async function download(){if(!session)return;try{const data=await request('/api/rooms/'+session.room+'?export=1',session),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='lantern-'+session.room+'-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Could not download.');}}
 async function survey(){if(!session)return;setBusy(true);try{await request('/api/rooms/'+session.room,session,{feedback:{stage:'post_match',answers:{fun:Number(fun),clarity:Number(clarity),meaningful_choices:Number(agency),play_again:again,comment}}});setFeedbackSaved(true);}catch(e){setError(e instanceof Error?e.message:'Feedback could not be saved.');}finally{setBusy(false);}}
 const send=(c:Choice)=>void commitChoice(c).catch(()=>{});
 const g=view?.game,p=view?.player??0,own=g?.sides[p],op=g?.sides[opposite(p)],ownActive=own&&own.active>=0?own.team[own.active]:null,opActive=op&&op.active>=0?op.team[op.active]:null;
 const locked=busy||!!g?.committed||!view?.joined||!g?.required;
 const choiceName=picked?.kind==='move'?MOVES[picked.move]?.name:picked&&(picked.kind==='lead'||picked.kind==='switch')&&own?SPECIES[own.team[picked.slot].monster_id].name:'';
 const outcome=g?.outcome;
 return <main className="game-shell">
 <header className="masthead"><a href="/" className="brand"><Sparkles aria-hidden="true"/><span>Lantern Marches</span></a><div className="header-actions"><span className="edition">FIRST CONTEST · V1</span><RulesDialog/></div></header>
 {error&&<div role="alert" className="error-banner">{error}</div>}
 {!ready?<div className="loading-screen"><LoaderCircle className="spin"/>Restoring your contest…</div>:!view?<><section className="lobby"><div className="lobby-intro"><span className="eyebrow">THE CONTEST GROUNDS</span><h1>Meet on the<br/>lantern road.</h1><p>Four companions, assigned by chance.<br/>Choose your moves. Read your rival. Find your way to victory.</p><div className="element-strip">{[Flame,Wind,Mountain,Droplets,Moon,Sun].map((Icon,i)=><span key={i} className={'type-mark type-'+['fire','air','earth','water','dark','light'][i]}><Icon size={20} aria-hidden="true"/></span>)}</div><div className="lobby-creatures"><CreatureArt id="N01"/><CreatureArt id="N04"/><CreatureArt id="N11"/></div></div><div className="room-panel"><div className="panel-heading"><Users size={22}/><h2>A private contest</h2></div><p>Create a room and invite one opponent. Both players receive their own random team.</p><Button className="main-button" size="lg" disabled={busy} onClick={()=>void openRoom().catch(()=>{})}>{busy?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>}Create a room</Button><div className="or-divider"><span>or join a friend</span></div><form onSubmit={e=>{e.preventDefault();void openRoom(code.trim()).catch(()=>{});}}><label htmlFor="room-code">Room code</label><div className="join-line"><Input id="room-code" autoComplete="off" placeholder="Enter room code" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))} maxLength={8}/><Button type="submit" variant="outline" disabled={busy||code.length!==8}><KeyRound size={16}/>Join</Button></div></form><p className="room-note">One blind redraw. Secret choices. No turn timer.</p><p className="subtle">For two people on separate devices or browser profiles.</p></div></section><footer className="lobby-footer"><span>FIRE · AIR · EARTH · WATER · DARK · LIGHT</span><span>Original creatures of the Lantern Marches</span></footer></>:g&&own&&<>
 <div className="contest-bar"><div className="room-identity"><span className="eyebrow">ROOM</span><strong>{view.room}</strong><Button variant="ghost" size="sm" aria-label="Copy invite link" onClick={()=>void copyInvite()}><Copy size={15}/></Button><span className="your-seat">You are Player {p+1}</span></div><div className="connection"><span className={'connection-dot '+(view.joined&&view.opponentOnline?'online':'')}/>{!view.joined?'Waiting for your opponent':view.opponentOnline?'Opponent connected':'Opponent away · contest saved'}</div></div>
 {notice&&<p className="notice" role="status">{notice}</p>}
 {!view.joined&&<div className="invite-banner"><Users size={20}/><div><strong>Invite someone to the contest.</strong><p>Share the room code or copy the invite link. You can inspect your team while you wait.</p></div><Button variant="outline" onClick={()=>void copyInvite()}><Copy size={15}/>Copy invite</Button></div>}
 {g.gate==='offer'?<section className="offer-section"><div className="section-heading"><div><span className="eyebrow">YOUR PRIVATE TEAM</span><h1>{g.committed?(own.redrawn?'Your redraw is final.':'Your team is locked in.'):'Four companions for the road.'}</h1><p>{g.committed?'Waiting for the other player’s team decision. Your offer stays private until both are ready.':'Inspect their stats and moves. Keep this team, or take one blind redraw before either team is revealed.'}</p></div><span className="round-pill">1 blind redraw</span></div><div className="team-grid">{own.team.map((mon,i)=><TeamCard key={i} mon={mon}/>)}</div>{!g.committed&&<div className="offer-footer"><div><label className="optional-question">Does this team give you a workable plan? <select aria-label="Team plan confidence" value={confidence} onChange={e=>setConfidence(e.target.value)}><option value="">Optional feedback</option><option value="yes">Yes</option><option value="unsure">Not sure yet</option><option value="no">No</option></select></label><p className="subtle">A redraw replaces all four and guarantees at least two different species. You must keep the new team.</p></div><div className="offer-buttons"><Button variant="outline" size="lg" disabled={locked} onClick={()=>setRedrawOpen(true)}><RefreshCw size={16}/>Blind redraw</Button><Button size="lg" disabled={locked} onClick={()=>send({kind:'keep'})}><Check size={17}/>Keep this team</Button></div></div>}{g.committed&&<div className="waiting-note" role="status"><LoaderCircle className="spin" size={17}/>Team decision committed. Your opponent’s decision stays secret.</div>}</section>:<>
 {outcome?<div className={'result-banner '+(outcome.winner===p?'victory':'')} role="status"><Sparkles size={26}/><div><h1>{outcome.winner===null?'A drawn contest.':outcome.winner===p?'The lanterns shine for you.':'Your rival carries the light.'}</h1><p>{outcome.winner===null?(outcome.reason==='turn_cap'?'The contest reached its 60-turn limit.':'Both final companions fell together.'):outcome.reason==='resign'?'The contest ended by resignation.':outcome.winner===p?'You knocked out all four opposing companions.':'Your rival knocked out your four companions.'} · {g.turn} turns</p></div></div>:<div className="battle-heading"><div><span className="eyebrow">{g.gate==='lead'?'THE OPENING':g.gate==='replace'?'A COMPANION FALLS':'THE CONTEST'}</span><h1>{g.gate==='lead'?'Choose your lead.':g.gate==='replace'?g.required?'Choose a replacement.':'Your opponent is choosing a replacement.':'Turn '+(g.turn+1)}</h1></div><span className="round-pill">{g.gate==='normal'?'Secret simultaneous choices':g.gate==='replace'?'Replacement · no turn spent':'Teams revealed · leads secret'}</span></div>}
 <div className="battle-layout"><div className="battle-main"><div className="battlefield"><div className="battle-scene-window"><div className="battle-scene"><img className="battle-background battle-background-wide" src="/battle/background.png?v=gray-v1" width={256} height={144} alt="" aria-hidden="true"/><img className="battle-background battle-background-narrow" src="/battle/background-mobile.png?v=gray-v1" width={176} height={144} alt="" aria-hidden="true"/>{ownActive&&<CreatureArt id={ownActive.monster_id} view="back" className={'combat-sprite player-sprite '+(ownActive.hp===0?'sprite-fainted':'')}/>} {opActive&&<CreatureArt id={opActive.monster_id} view="front" className={'combat-sprite opponent-sprite '+(opActive.hp===0?'sprite-fainted':'')}/>}</div></div><div className="battle-status"><ActiveCard mon={ownActive} side="YOUR ACTIVE"/><div className="versus"><span>VS</span></div><ActiveCard mon={opActive} side="OPPONENT’S ACTIVE"/></div></div>
 {!outcome&&<section className="decision-panel"><div className="decision-heading"><h2>{g.committed?'Choice committed':g.gate==='lead'?'Who leads the way?':g.gate==='replace'?g.required?'Send your next companion':'Waiting for a replacement':'What is your move?'}</h2><span className="subtle">{g.committed?'Waiting for the other player':g.gate==='normal'?'Switches → priority → Speed':'Your choice is secret'}</span></div>
 {g.committed||!g.required?<div className="waiting-note" role="status"><LoaderCircle className="spin" size={18}/>{g.committed?'Your choice is locked. The contest waits for the other player.':'Your active stays in place while your opponent replaces theirs.'}</div>:<>
 {g.gate==='normal'&&ownActive&&<div className="move-grid">{[...SETS[ownActive.set_id].move_ids,...(g.legal.some(c=>c.kind==='move'&&c.move===ownActive.fallback)?[ownActive.fallback]:[])].map(id=>{const m=MOVES[id],choice:Choice={kind:'move',move:id},can=g.legal.some(c=>choiceKey(c)===choiceKey(choice)),selected=picked&&choiceKey(picked)===choiceKey(choice),f=opActive?effectiveness(m.type,SPECIES[opActive.monster_id].type):[1,1];return <button key={id} data-move-type={m.type??'untyped'} className={'move-choice '+(selected?'selected':'')} disabled={!can||busy} onClick={()=>setPicked(choice)} aria-pressed={!!selected}><div className="move-top"><strong>{m.name}</strong><span>{m.max_uses===null?'∞':ownActive.uses[id]+'/'+m.max_uses}</span></div><div className="move-tags"><TypeBadge type={m.type}/><span>{m.category}</span>{m.priority>0&&<span className="priority-tag">+1 priority</span>}</div><p>{m.power&&opActive?<>Power {m.power} · normal hit {Math.min(opActive.hp,damage(ownActive,opActive,id))}{f[0]>f[1]?' · strong':f[0]<f[1]?' · resisted':''}</>:m.description}</p></button>;})}</div>}
 {g.gate==='lead'&&<label className="optional-question">Does your final team offer a plan? <select aria-label="Final team plan confidence" value={confidence} onChange={e=>setConfidence(e.target.value)}><option value="">Optional feedback</option><option value="yes">Yes</option><option value="unsure">Not sure yet</option><option value="no">No</option></select></label>}
 <div className="selection-roster">{own.team.map((mon,i)=>{const c:Choice={kind:g.gate==='lead'?'lead':'switch',slot:i},can=g.legal.some(x=>choiceKey(x)===choiceKey(c)),selected=picked&&choiceKey(picked)===choiceKey(c);return <div key={i} className={'bench-tile '+(mon.hp===0?'fainted ':'')+(i===own.active?'is-active':'')}><button disabled={!can||busy} className={selected?'selected':''} onClick={()=>setPicked(c)} aria-pressed={!!selected}><CreatureArt id={mon.monster_id} view="icon"/><span><strong>{SPECIES[mon.monster_id].name}</strong><small>{mon.hp===0?'Knocked out':i===own.active?'Active':g.gate==='lead'?'Choose lead':'Switch in'} · {mon.hp}/{SPECIES[mon.monster_id].stats.health}</small></span>{!!selected&&<Check size={15}/>}</button><MonsterDetails mon={mon} compact/></div>;})}</div>
 <div className="commit-bar"><div><strong>{picked?(picked.kind==='move'?'Use ':'Send in ')+choiceName:'Select an action above'}</strong><p>Commitment is final. Your opponent cannot see it before resolution.</p></div><Button size="lg" disabled={busy||!picked||!view.joined} onClick={()=>picked&&send(picked)}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}Commit choice</Button></div></>}
 {(g.committed||!g.required)&&<div className="selection-roster">{own.team.map((mon,i)=><div className="opponent-tile" key={i}><CreatureArt id={mon.monster_id} view="icon"/><div><strong>{SPECIES[mon.monster_id].name}</strong><span>{mon.hp}/{SPECIES[mon.monster_id].stats.health} Health</span></div><MonsterDetails mon={mon} compact/></div>)}</div>}
 </section>}
 <section className="opponent-roster"><div className="decision-heading"><h2>Opponent’s team</h2><span className="subtle">All sets are public</span></div><div className="opponent-tiles">{op?.team.map((mon,i)=><div key={i} className={'opponent-tile '+(mon.hp===0?'fainted':'')}><CreatureArt id={mon.monster_id} view="icon"/><div><strong>{SPECIES[mon.monster_id].name}</strong><TypeBadge type={SPECIES[mon.monster_id].type}/><span>{mon.hp}/{SPECIES[mon.monster_id].stats.health} Health {i===op.active?'· active':''}</span></div><MonsterDetails mon={mon} compact/></div>)}</div></section>
 </div><aside className="battle-record"><div className="record-heading"><h2>The battle record</h2><span>{g.turn} turns</span></div><div className="record-events" aria-label="Resolved battle events">{g.events.length?g.events.slice().reverse().map((e,i)=><div key={g.events.length-i} className={'record-event event-'+e.kind}><span className="event-turn">{e.turn===0?'Start':'T'+e.turn}</span><p>{e.text}</p></div>):<p className="subtle">Resolved actions will appear here.</p>}</div></aside></div>
 {outcome?<section className="post-match"><div className="post-actions"><Button onClick={()=>void openRoom().catch(()=>{})} disabled={busy}><Sparkles size={16}/>Create another contest</Button><Button variant="outline" onClick={()=>void download()}><Download size={16}/>Download battle record</Button></div>{feedbackSaved?<p className="notice" role="status">Playtest feedback saved. Thank you for helping shape the contest.</p>:<form className="survey" onSubmit={e=>{e.preventDefault();void survey();}}><h2>Help shape the next contest</h2><p className="subtle">Optional playtest feedback · ratings from 1 (low) to 5 (high)</p><div className="survey-fields">{[['Enjoyment',fun,setFun],['Rule clarity',clarity,setClarity],['Meaningful choices',agency,setAgency]].map(([label,value,setter])=><label key={label as string}>{label as string}<select required value={value as string} onChange={e=>(setter as (s:string)=>void)(e.target.value)}><option value="">Choose</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label>)}<label>Play again?<select required value={again} onChange={e=>setAgain(e.target.value)}><option value="">Choose</option><option value="yes">Yes</option><option value="unsure">Maybe</option><option value="no">No</option></select></label></div><label htmlFor="playtest-comment">A satisfying choice, a frustrating moment, or an unclear rule</label><textarea id="playtest-comment" maxLength={1500} value={comment} onChange={e=>setComment(e.target.value)}/><Button type="submit" variant="outline" disabled={busy||!fun||!clarity||!agency||!again}>Save feedback</Button></form>}</section>:<div className="contest-footer"><span>Effects count active turn ends · 60-turn limit · all moves hit</span><Button variant="ghost" size="sm" disabled={busy||!view.joined||g.committed} onClick={()=>setResignOpen(true)}><Flag size={14}/>Resign contest</Button></div>}
 </>}
 </>}
 <Dialog open={redrawOpen} onOpenChange={setRedrawOpen}><DialogContent><DialogTitle>Take your one blind redraw?</DialogTitle><DialogDescription>All four companions will be replaced. At least two species will change. The new team is final, and you will not see your opponent’s team first.</DialogDescription><label htmlFor="redraw-reason" className="subtle">Why redraw? (optional playtest note)</label><Input id="redraw-reason" maxLength={500} value={comment} onChange={e=>setComment(e.target.value)} placeholder="What is missing from this team?"/><DialogFooter><Button variant="outline" onClick={()=>setRedrawOpen(false)}>Keep reviewing</Button><Button disabled={busy} onClick={()=>send({kind:'redraw'})}>Replace my team</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={resignOpen} onOpenChange={setResignOpen}><DialogContent><DialogTitle>Resign this contest?</DialogTitle><DialogDescription>Your opponent will win. Closing the browser instead pauses the contest until you return.</DialogDescription><DialogFooter><Button variant="outline" onClick={()=>setResignOpen(false)}>Continue playing</Button><Button disabled={busy} onClick={()=>send({kind:'resign'})}>Resign</Button></DialogFooter></DialogContent></Dialog>
 </main>;
}
